package com.fencecad.ui.screens

import android.content.Intent
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.fencecad.engine.CadExportManager
import com.fencecad.engine.PdfReportGenerator
import com.fencecad.engine.ProcurementEngine
import com.fencecad.engine.SimulationEngine
import com.fencecad.model.FenceProject
import com.fencecad.model.FenceType
import com.fencecad.model.ProcurementItem
import com.fencecad.ui.theme.*
import kotlin.math.*

@Composable
fun ProcurementScreen(
    currentProject: FenceProject,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current

    // Calculation parameters with interactive adjusters
    var perimeterLength by remember(currentProject.id) {
        val totalWireM = currentProject.wires.sumOf { it.lengthMeters.toDouble() }
        mutableStateOf(if (totalWireM > 0) ceil(totalWireM).toInt() else 100)
    }
    var strandCount by remember(currentProject.id) { mutableStateOf(8) }
    var cornerCount by remember(currentProject.id) {
        val count = currentProject.nodes.count { it.type == com.fencecad.model.ComponentType.CORNER }
        mutableStateOf(if (count > 0) count else 4)
    }
    var gateCount by remember(currentProject.id) {
        val count = currentProject.nodes.count { it.type == com.fencecad.model.ComponentType.GATE }
        mutableStateOf(if (count > 0) count else 1)
    }
    var postSpacing by remember { mutableStateOf(3) } // meters
    var fenceType by remember(currentProject.id) { mutableStateOf(currentProject.fenceType) }

    val procurementResults = remember(perimeterLength, strandCount, cornerCount, gateCount, postSpacing, fenceType) {
        ProcurementEngine.calculateProcurement(
            currentProject.copy(fenceType = fenceType),
            postSpacingMeters = postSpacing,
            strandCount = strandCount
        )
    }

    val bomItems = remember(procurementResults) {
        ProcurementEngine.generateDetailedBOQ(procurementResults)
    }

    fun shareProcurementText() {
        val report = buildString {
            appendLine("═══════════════════════════════════════════")
            appendLine(" FENCESENSE - MATERIAL BILL OF QUANTITIES (BOQ)")
            appendLine(" SANS 10222-3 COMPLIANT PROCUREMENT ESTIMATE")
            appendLine("═══════════════════════════════════════════")
            appendLine("Project: ${currentProject.name}")
            appendLine("Application: ${fenceType.displayName.uppercase()}")
            appendLine("Perimeter: ${perimeterLength}m | Strands: $strandCount | Corners: $cornerCount | Gates: $gateCount")
            appendLine("───────────────────────────────────────────")
            appendLine()

            val byCat = bomItems.groupBy { it.category }
            for ((cat, catItems) in byCat) {
                appendLine("[$cat]")
                for (item in catItems) {
                    appendLine(" • ${item.quantity} ${item.unit} - ${item.item}")
                    appendLine("   Note: ${item.notes}")
                }
                appendLine()
            }
            appendLine("───────────────────────────────────────────")
            appendLine("Generated by FenceSense Android CAD Suite")
        }

        val sendIntent = Intent().apply {
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_TEXT, report)
            type = "text/plain"
        }
        val shareIntent = Intent.createChooser(sendIntent, "Share Bill of Materials Text")
        context.startActivity(shareIntent)
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(BgDark)
    ) {
        // TOP HEADER
        Surface(
            color = BgPanel,
            tonalElevation = 2.dp,
            modifier = Modifier.fillMaxWidth()
        ) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 14.dp, vertical = 10.dp),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column {
                    Text(
                        text = "📦 MATERIAL PROCUREMENT & BOQ",
                        style = MaterialTheme.typography.titleMedium,
                        color = AmberEnergizer,
                        fontWeight = FontWeight.Bold
                    )
                    Text(
                        text = "SANS 10222-3 Certified Hardware Sizing for ${currentProject.name}",
                        style = MaterialTheme.typography.bodySmall,
                        color = TextMuted
                    )
                }

                Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    Button(
                        onClick = {
                            val network = SimulationEngine.buildCircuitFromProject(currentProject)
                            val sim = SimulationEngine.runSimulation(network)
                            PdfReportGenerator.exportAndShareCoCPdf(context, currentProject, sim, procurementResults)
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = AmberEnergizer),
                        shape = RoundedCornerShape(6.dp),
                        contentPadding = PaddingValues(horizontal = 8.dp, vertical = 4.dp),
                        modifier = Modifier.height(32.dp)
                    ) {
                        Icon(Icons.Default.PictureAsPdf, contentDescription = null, tint = Color.Black, modifier = Modifier.size(14.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text("PDF CoC", color = Color.Black, fontWeight = FontWeight.Bold, style = MaterialTheme.typography.labelSmall)
                    }

                    IconButton(
                        onClick = { shareProcurementText() },
                        modifier = Modifier
                            .size(32.dp)
                            .background(BgCard, RoundedCornerShape(6.dp))
                            .border(1.dp, BorderDark, RoundedCornerShape(6.dp))
                    ) {
                        Icon(Icons.Default.Share, contentDescription = "Share Text", tint = TextMuted, modifier = Modifier.size(16.dp))
                    }
                }
            }
        }

        // INTERACTIVE PARAMETER ADJUSTERS
        Surface(
            color = BgCard,
            modifier = Modifier
                .fillMaxWidth()
                .padding(10.dp),
            shape = RoundedCornerShape(10.dp),
            border = BorderStroke(1.dp, BorderDark)
        ) {
            Column(modifier = Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("⚙ FENCE DIMENSIONS & TOPOLOGY", style = MaterialTheme.typography.labelSmall, color = AmberEnergizer)

                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .horizontalScroll(rememberScrollState()),
                    horizontalArrangement = Arrangement.spacedBy(14.dp)
                ) {
                    ParamStepper(label = "PERIMETER", value = "${perimeterLength}m", onDec = { perimeterLength = max(10, perimeterLength - 10) }, onInc = { perimeterLength += 10 })
                    ParamStepper(label = "STRANDS", value = "$strandCount", onDec = { strandCount = max(2, strandCount - 2) }, onInc = { strandCount = min(30, strandCount + 2) })
                    ParamStepper(label = "CORNERS", value = "$cornerCount", onDec = { cornerCount = max(2, cornerCount - 1) }, onInc = { cornerCount += 1 })
                    ParamStepper(label = "GATES", value = "$gateCount", onDec = { gateCount = max(0, gateCount - 1) }, onInc = { gateCount += 1 })
                    ParamStepper(label = "POST SPACING", value = "${postSpacing}m", onDec = { postSpacing = max(2, postSpacing - 1) }, onInc = { postSpacing = min(6, postSpacing + 1) })
                }
            }
        }

        // BOM LIST
        LazyColumn(
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth()
                .padding(horizontal = 10.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            val byCat = bomItems.groupBy { it.category }
            for ((cat, catItems) in byCat) {
                item {
                    Text(
                        text = "▶ $cat",
                        style = MaterialTheme.typography.labelSmall,
                        color = AmberEnergizer,
                        modifier = Modifier.padding(top = 8.dp, bottom = 2.dp)
                    )
                }
                items(catItems) { item ->
                    Card(
                        colors = CardDefaults.cardColors(containerColor = BgCard),
                        border = BorderStroke(1.dp, BorderDark),
                        shape = RoundedCornerShape(8.dp),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(12.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Surface(
                                color = AmberDim,
                                shape = RoundedCornerShape(6.dp),
                                border = BorderStroke(1.dp, AmberEnergizer),
                                modifier = Modifier.size(46.dp)
                            ) {
                                Column(
                                    modifier = Modifier.fillMaxSize(),
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.Center
                                ) {
                                    Text("${item.quantity}", style = MaterialTheme.typography.titleMedium, color = AmberEnergizer, fontWeight = FontWeight.Bold)
                                    Text(item.unit, style = MaterialTheme.typography.labelSmall, color = TextMuted, fontSize = 7.sp)
                                }
                            }

                            Spacer(modifier = Modifier.width(12.dp))

                            Column(modifier = Modifier.weight(1f)) {
                                Text(item.item, style = MaterialTheme.typography.titleSmall, color = TextPrimary)
                                Text(item.notes, style = MaterialTheme.typography.bodySmall, color = TextMuted, modifier = Modifier.padding(top = 2.dp))
                            }
                        }
                    }
                }
            }
            item {
                Spacer(modifier = Modifier.height(20.dp))
            }
        }
    }
}

@Composable
private fun ParamStepper(
    label: String,
    value: String,
    onDec: () -> Unit,
    onInc: () -> Unit
) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Text(label, style = MaterialTheme.typography.labelSmall, color = TextMuted, fontSize = 8.sp)
        Row(
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier.padding(top = 2.dp)
        ) {
            Box(
                modifier = Modifier
                    .size(24.dp)
                    .background(BgDark, CircleShape)
                    .border(1.dp, BorderDark, CircleShape)
                    .clickable { onDec() },
                contentAlignment = Alignment.Center
            ) {
                Text("-", color = TextPrimary, fontWeight = FontWeight.Bold)
            }
            Text(
                text = value,
                style = MaterialTheme.typography.titleSmall,
                color = TextPrimary,
                modifier = Modifier.padding(horizontal = 8.dp)
            )
            Box(
                modifier = Modifier
                    .size(24.dp)
                    .background(BgDark, CircleShape)
                    .border(1.dp, BorderDark, CircleShape)
                    .clickable { onInc() },
                contentAlignment = Alignment.Center
            ) {
                Text("+", color = TextPrimary, fontWeight = FontWeight.Bold)
            }
        }
    }
}
